# Generated by Django 5.2.6 on 2025-09-20 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cartridge',
            fields=[
                ('number', models.CharField(primary_key=True, serialize=False, unique=True, verbose_name='Номенклатура')),
                ('article', models.CharField(unique=True, verbose_name='Артикул')),
                ('caption', models.TextField(blank=True, default='', verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Имя принтера')),
            ],
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateField(auto_created=True, unique=True, verbose_name='Дата инвентаризации')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, verbose_name='Количество')),
                ('cartridge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage.cartridge', verbose_name='Картридж')),
                ('snapshot', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='storage.snapshot', verbose_name='Снимок')),
            ],
        ),
    ]
