# Generated by Django 5.2.6 on 2025-09-23 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartridge',
            name='article',
            field=models.CharField(verbose_name='Артикул'),
        ),
    ]
