# Generated by Django 5.2.6 on 2025-09-29 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_alter_cartridge_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snapshot',
            name='dt',
            field=models.DateField(auto_created=True, verbose_name='Дата инвентаризации'),
        ),
    ]
