# Generated by Django 5.2.6 on 2025-09-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_alter_snapshot_dt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartridge',
            options={'ordering': ['-priority']},
        ),
        migrations.AddField(
            model_name='cartridge',
            name='priority',
            field=models.IntegerField(default=0, verbose_name='Приоритет'),
        ),
    ]
