# Generated by Django 5.2.6 on 2025-10-01 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_alter_cartridge_options_cartridge_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartridge',
            name='article',
            field=models.CharField(max_length=128, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='cartridge',
            name='number',
            field=models.CharField(max_length=16, primary_key=True, serialize=False, unique=True, verbose_name='Номенклатура'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Имя принтера'),
        ),
    ]
