# Generated by Django 5.2.6 on 2025-10-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_alter_cartridge_article_alter_cartridge_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartridge',
            name='full_caption',
            field=models.TextField(blank=True, default='', verbose_name='Полное наименование'),
        ),
        migrations.AlterField(
            model_name='cartridge',
            name='caption',
            field=models.TextField(blank=True, default='', verbose_name='Наименование'),
        ),
    ]
